export const brandColors = {
  'stroke-dark-soft': '#E0E2E7',
  'stroke-gray': '#667085',
  heading: '#090C18',
  'heading-200': '#171B1D',
  'text-gray': '#667085',
  'fill-dark-soft': '#F0F1F3',
  'fill-gray-light': '#C2C6CE',
  'text-dark': '#1B2037',
  'fill-surface': '#FAFAFA',
  'fill-outermost': '#171A28',
  'stroke-outermost': '#242A46',
  'dark-text-gray': '#6A749C',
  'dark-fill-secondary': '#4006AA',
  'dark-bg-space': '#202431',
  'very-light-blue': '#6E4AFF',
  'bright-lavender': '#A78BF6',
  'semantic-accent-light': '#FFF8F7',
  'semantic-accent': '#D73E3D',
  'semantic-accent-300': '#E5372B',
  'semantic-accent-400': '#C72D22',
  'semantic-accent-dark': '#7F0800',
  'semantic-accent-dark-300': '#431815',
  'semantic-success': '#08B94E',
  'semantic-success-light': '#F4FCF7',

  'icon-light-fixed': 'hsl(var(--icon-light-fixed))',
  'icon-dark': 'hsl(var(--icon-dark))',
  'icon-gray': 'hsl(var(--icon-gray))',
  'icon-secondary': 'hsl(var(--icon-secondary))',
  'icon-accent': 'hsl(var(--icon-accent))',
  'icon-info': 'hsl(var(--icon-info))',
  'icon-positive': 'hsl(var(--icon-positive))',
  'icon-positive-dark': 'hsl(var(--icon-positive-dark))',
  'icon-negative': 'hsl(var(--icon-negative))',
  'icon-negative-dark': 'hsl(var(--icon-negative-dark))',
  'icon-warning': 'hsl(var(--icon-warning))',
  'icon-warning-dark': 'hsl(var(--icon-warning-dark))',
  'icon-disabled': 'hsl(var(--icon-disabled))',
  'icon-hover-dark': 'hsl(var(--icon-hover-dark))',
  'icon-hover-gray': 'hsl(var(--icon-hover-gray))',
  'icon-hover-secondary': 'hsl(var(--icon-hover-secondary))',
  'icon-hover-accent': 'hsl(var(--icon-hover-accent))',
  'icon-hover-info': 'hsl(var(--icon-hover-info))',
  'icon-hover-positive': 'hsl(var(--icon-hover-positive))',
  'icon-hover-negative': 'hsl(var(--icon-hover-negative))',
  'icon-hover-warning': 'hsl(var(--icon-hover-warning))',
  'background-fill-surface': 'hsl(var(--background-fill-surface))',
  'background-fill-outermost': 'hsl(var(--background-fill-outermost))',
  'background-fill-middle': 'hsl(var(--background-fill-middle))',
  'background-fill-inner': 'hsl(var(--background-fill-inner))',
  'background-fill-central': 'hsl(var(--background-fill-central))',
  'background-fill-heart': 'hsl(var(--background-fill-heart))',
  'background-stroke-surface': 'hsl(var(--background-stroke-surface))',
  'component-progressbar-container':
    'hsl(var(--component-progressbar-container))',
  'background-stroke-outermost': 'hsl(var(--background-stroke-outermost))',
  'background-stroke-middle': 'hsl(var(--background-stroke-middle))',
  'background-stroke-inner': 'hsl(var(--background-stroke-inner))',
  'background-stroke-central': 'hsl(var(--background-stroke-central))',
  'background-stroke-heart': 'hsl(var(--background-stroke-heart))',
  'typo-display': 'hsl(var(--typo-display))',
  'typo-display-light': 'hsl(var(--typo-display-light))',
  'typo-heading': 'hsl(var(--typo-heading))',
  'typo-heading-light': 'hsl(var(--typo-heading-light))',
  'typo-caption': 'hsl(var(--typo-caption))',
  'typo-caption-light': 'hsl(var(--typo-caption-light))',
  'typo-caption-soft': 'hsl(var(--typo-caption-soft))',
  'typo-body': 'hsl(var(--typo-body))',
  'typo-body-light': 'hsl(var(--typo-body-light))',
  'typo-body-soft': 'hsl(var(--typo-body-soft))',
  'component-text-light-fixed': 'hsl(var(--component-text-light-fixed))',
  'component-text-light': 'hsl(var(--component-text-light))',
  'component-text-dark': 'hsl(var(--component-text-dark))',
  'component-text-dark-hover': 'hsl(var(--component-text-dark-hover))',
  'component-text-gray': 'hsl(var(--component-text-gray))',
  'component-text-gray-hover': 'hsl(var(--component-text-gray-hover))',
  'component-text-secondary': 'hsl(var(--component-text-secondary))',
  'component-text-secondary-hover':
    'hsl(var(--component-text-secondary-hover))',
  'component-text-accent': 'hsl(var(--component-text-accent))',
  'component-text-accent-hover': 'hsl(var(--component-text-accent-hover))',
  'component-text-info': 'hsl(var(--component-text-info))',
  'component-text-info-hover': 'hsl(var(--component-text-info-hover))',
  'component-text-positive': 'hsl(var(--component-text-positive))',
  'component-text-positive-dark': 'hsl(var(--component-text-positive-dark))',
  'component-text-positive-hover': 'hsl(var(--component-text-positive-hover))',
  'component-text-negative': 'hsl(var(--component-text-negative))',
  'component-text-negative-dark': 'hsl(var(--component-text-negative-dark))',
  'component-text-negative-hover': 'hsl(var(--component-text-negative-hover))',
  'component-text-warning': 'hsl(var(--component-text-warning))',
  'component-text-warning-dark': 'hsl(var(--component-text-warning-dark))',
  'component-text-warning-hover': 'hsl(var(--component-text-warning-hover))',
  'component-text-disabled': 'hsl(var(--component-text-disabled))',
  'component-fill-light-fixed': 'hsl(var(--component-fill-light-fixed))',
  'component-fill-light': 'hsl(var(--component-fill-light))',
  'component-fill-gray': 'hsl(var(--component-fill-gray))',
  'component-fill-gray-light': 'hsl(var(--component-fill-gray-light))',
  'component-fill-gray-soft': 'hsl(var(--component-fill-gray-soft))',
  'component-fill-reversed': 'hsl(var(--component-fill-reversed))',
  'component-fill-dark': 'hsl(var(--component-fill-dark))',
  'component-fill-dark-soft': 'hsl(var(--component-fill-dark-soft))',
  'component-fill-secondary': 'hsl(var(--component-fill-secondary))',
  'component-fill-secondary-soft': 'hsl(var(--component-fill-secondary-soft))',
  'component-fill-accent': 'hsl(var(--component-fill-accent))',
  'component-fill-accent-soft': 'hsl(var(--component-fill-accent-soft))',
  'component-fill-info': 'hsl(var(--component-fill-info))',
  'component-fill-info-soft': 'hsl(var(--component-fill-info-soft))',
  'component-fill-positive': 'hsl(var(--component-fill-positive))',
  'component-fill-positive-soft': 'hsl(var(--component-fill-positive-soft))',
  'component-fill-negative': 'hsl(var(--component-fill-negative))',
  'component-fill-negative-soft': 'hsl(var(--component-fill-negative-soft))',
  'component-fill-warning': 'hsl(var(--component-fill-warning))',
  'component-fill-warning-soft': 'hsl(var(--component-fill-warning-soft))',
  'component-fill-disabled': 'hsl(var(--component-fill-disabled))',
  'component-stroke-light-fixed': 'hsl(var(--component-stroke-light-fixed))',
  'component-stroke-light': 'hsl(var(--component-stroke-light))',
  'component-stroke-dark': 'hsl(var(--component-stroke-dark))',
  'component-stroke-dark-soft': 'hsl(var(--component-stroke-dark-soft))',
  'component-stroke-gray': 'hsl(var(--component-stroke-gray))',
  'component-stroke-gray-soft': 'hsl(var(--component-stroke-gray-soft))',
  'component-stroke-secondary': 'hsl(var(--component-stroke-secondary))',
  'component-stroke-secondary-soft':
    'hsl(var(--component-stroke-secondary-soft))',
  'component-stroke-accent': 'hsl(var(--component-stroke-accent))',
  'component-stroke-accent-soft': 'hsl(var(--component-stroke-accent-soft))',
  'component-stroke-info': 'hsl(var(--component-stroke-info))',
  'component-stroke-info-soft': 'hsl(var(--component-stroke-info-soft))',
  'component-stroke-positive': 'hsl(var(--component-stroke-positive))',
  'component-stroke-positive-light':
    'hsl(var(--component-stroke-positive-light))',
  'component-stroke-positive-dark':
    'hsl(var(--component-stroke-positive-dark))',
  'component-stroke-positive-soft':
    'hsl(var(--component-stroke-positive-soft))',
  'component-stroke-negative': 'hsl(var(--component-stroke-negative))',
  'component-stroke-negative-light':
    'hsl(var(--component-stroke-negative-light))',
  'component-stroke-negative-dark':
    'hsl(var(--component-stroke-negative-dark))',
  'component-stroke-negative-soft':
    'hsl(var(--component-stroke-negative-soft))',
  'component-stroke-warning': 'hsl(var(--component-stroke-warning))',
  'component-stroke-warning-light':
    'hsl(var(--component-stroke-warning-light))',
  'component-stroke-warning-dark': 'hsl(var(--component-stroke-warning-dark))',
  'component-stroke-warning-soft': 'hsl(var(--component-stroke-warning-soft))',
  'component-stroke-disabled': 'hsl(var(--component-stroke-disabled))',
  'component-hover-light-fixed': 'hsl(var(--component-hover-light-fixed))',
  'component-hover-light': 'hsl(var(--component-hover-light))',
  'component-hover-dark': 'hsl(var(--component-hover-dark))',
  'component-hover-dark-light': 'hsl(var(--component-hover-dark-light))',
  'component-hover-dark-soft': 'hsl(var(--component-hover-dark-soft))',
  'component-hover-gray': 'hsl(var(--component-hover-gray))',
  'component-hover-gray-light': 'hsl(var(--component-hover-gray-light))',
  'component-hover-gray-soft': 'hsl(var(--component-hover-gray-soft))',
  'component-hover-secondary': 'hsl(var(--component-hover-secondary))',
  'component-hover-secondary-light':
    'hsl(var(--component-hover-secondary-light))',
  'component-hover-secondary-soft':
    'hsl(var(--component-hover-secondary-soft))',
  'component-hover-accent': 'hsl(var(--component-hover-accent))',
  'component-hover-accent-light': 'hsl(var(--component-hover-accent-light))',
  'component-hover-accent-soft': 'hsl(var(--component-hover-accent-soft))',
  'component-hover-info': 'hsl(var(--component-hover-info))',
  'component-hover-info-light': 'hsl(var(--component-hover-info-light))',
  'component-hover-info-soft': 'hsl(var(--component-hover-info-soft))',
  'component-hover-positive': 'hsl(var(--component-hover-positive))',
  'component-hover-positive-light':
    'hsl(var(--component-hover-positive-light))',
  'component-hover-positive-soft': 'hsl(var(--component-hover-positive-soft))',
  'component-hover-negative': 'hsl(var(--component-hover-negative))',
  'component-hover-negative-light':
    'hsl(var(--component-hover-negative-light))',
  'component-hover-negative-soft': 'hsl(var(--component-hover-negative-soft))',
  'component-hover-warning': 'hsl(var(--component-hover-warning))',
  'component-hover-warning-light': 'hsl(var(--component-hover-warning-light))',
  'component-hover-warning-soft': 'hsl(var(--component-hover-warning-soft))',
  'component-fill-default-chart': 'hsl(var(--background-fill-default-chart))',
  'component-fill-sensor': 'hsl(var(--component-fill-sensor))',
}

export const dark = {}
