import { ChartType, Orientation } from '@/widget-models/chart'
import { WidgetType } from '@/widget-models/widget'
import { Layout } from 'react-grid-layout'
import { v4 as uuidv4 } from 'uuid'
import { TimeFormat } from './date-format'
import { GaugeType } from '@/widget-models/gauge'
import { OPERATORS } from '@/containers/dashboard/components/widget-selected/components/table-widget/table.const'

const SMART_FLEET_MONITOR_LAYOUT: Layout[] = [
  {
    x: 0,
    y: 0,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
    i: '1',
  },
  {
    x: 4,
    y: 0,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
    i: '2',
  },
  {
    x: 0,
    y: 3,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
    i: '3',
  },
  {
    x: 2,
    y: 3,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
    i: '4',
  },
  {
    x: 4,
    y: 3,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
    i: '5',
  },
  {
    i: '6',
    x: 0,
    y: 6,
    w: 6,
    h: 4,
    minW: 6,
    minH: 4,
  },
  {
    i: '7',
    x: 0,
    y: 9,
    w: 6,
    h: 3,
    minW: 4,
    minH: 3,
  },
  {
    i: '8',
    x: 0,
    y: 12,
    w: 4,
    h: 3,
    minW: 4,
    minH: 3,
  },
  {
    i: '9',
    x: 5,
    y: 14,
    w: 2,
    h: 3,
    minW: 2,
    minH: 3,
  },
  {
    i: '10',
    x: 0,
    y: 17,
    w: 3,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '11',
    x: 4,
    y: 17,
    w: 3,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '12',
    x: 0,
    y: 20,
    w: 6,
    h: 1,
    minW: 3,
  },
  {
    i: '13',
    x: 0,
    y: 21,
    w: 3,
    h: 1,
  },
  {
    i: '14',
    x: 4,
    y: 21,
    w: 3,
    h: 1,
  },
]

const CUSTOM_COLOR_LAYOUT: Layout[] = [
  {
    i: '1',
    x: 0,
    y: 0,
    w: 6,
    h: 1,
    minW: 3,
  },
  {
    i: '2',
    x: 0,
    y: 1,
    w: 6,
    h: 4,
    minH: 4,
    minW: 4,
  },
  {
    i: '3',
    x: 0,
    y: 5,
    w: 4,
    h: 1,
    minW: 4,
  },
  {
    i: '4',
    x: 0,
    y: 6,
    w: 4,
    h: 1,
    minW: 4,
  },
  {
    i: '5',
    x: 5,
    y: 5,
    w: 2,
    h: 2,
  },
  {
    i: '6',
    x: 0,
    y: 7,
    w: 6,
    h: 1,
    minW: 3,
  },
  {
    i: '7',
    x: 0,
    y: 8,
    w: 6,
    h: 4,
    minW: 6,
    minH: 4,
  },
  {
    i: '8',
    x: 0,
    y: 13,
    w: 6,
    h: 1,
    minW: 3,
  },
  {
    i: '9',
    x: 0,
    y: 13,
    w: 3,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '10',
    x: 3,
    y: 13,
    w: 3,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '11',
    x: 0,
    y: 16,
    w: 6,
    h: 4,
    minW: 4,
    minH: 2,
  },
]

export const DEFAULT_MONITOR_LAYOUT: Layout[] = [
  {
    i: '1',
    x: 0,
    y: 0,
    w: 3,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '2',
    x: 3,
    y: 0,
    w: 3,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '3',
    x: 0,
    y: 4,
    w: 6,
    h: 3,
    minW: 3,
    minH: 3,
  },
  {
    i: '4',
    x: 0,
    y: 7,
    w: 6,
    h: 4,
    minW: 3,
    minH: 4,
  },
  {
    i: '5',
    x: 0,
    y: 11,
    w: 4,
    h: 1,
    minW: 3,
    minH: 1,
  },
  {
    i: '6',
    x: 0,
    y: 12,
    w: 4,
    h: 1,
    minW: 3,
    minH: 1,
  },
  {
    i: '7',
    x: 5,
    y: 11,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: '8',
    x: 0,
    y: 13,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: '9',
    x: 3,
    y: 13,
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: '10',
    x: 0,
    y: 15,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: '11',
    x: 2,
    y: 15,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: '12',
    x: 4,
    y: 15,
    w: 2,
    h: 2,
    minW: 2,
    minH: 2,
  },
  {
    i: '13',
    x: 0,
    y: 17,
    w: 6,
    h: 4,
    minW: 3,
    minH: 2,
  },
]

export const DEMO_WIDGET_DASHBOARD = [
  {
    id: uuidv4(),
    dashboardId: 1,
    widgets: [
      {
        id: '1',
        type: WidgetType.Unit,
        title: 'Current Speed',
        value: 70,
        unit: 'km/h',
        status: 'On',
      },
      {
        id: '2',
        type: WidgetType.Unit,
        title: 'Total Trip',
        value: 12,
        unit: 'trips',
      },
      {
        id: '3',
        type: WidgetType.Unit,
        title: 'Min. Speed of today',
        value: 0,
        unit: 'km/h',
      },
      {
        id: '4',
        type: WidgetType.Unit,
        title: 'AVG. Speed of today',
        value: 84,
        unit: 'km/h',
      },
      {
        id: '5',
        type: WidgetType.Unit,
        title: 'Max. Speed of today',
        value: 125,
        unit: 'km/h',
      },
      {
        id: '6',
        type: WidgetType.Chart,
        title: 'Humidity and Temperature',
        showXGrid: true,
        orientation: Orientation.Left,
        format: TimeFormat.TIME_24H,
        hideAxis: false,
        sources: [
          {
            legend: 'Humidity',
            field: 'humidity',
            color: 'FAAFC6',
            show_legend: true,
            chart_type: ChartType.AreaChart,
            device_id: '1',
          },
          {
            legend: 'Temperature',
            field: 'temperature',
            color: 'FA8750',
            show_legend: true,
            chart_type: ChartType.AreaChart,
            device_id: '1',
          },
        ],
      },
      {
        id: '7',
        type: WidgetType.Map,
        title: 'Current Location',
        latitude: 16.05198423790203,
        longitude: 108.21679652348709,
        map_type: 'map',
      },
      {
        id: '8',
        type: WidgetType.Table,
        widget_info: {
          name: 'All Devices Status',
          appearance: {
            show_value: true,
          },
        },
        source: [
          {
            device_id: '1',
            device_name: 'RAK Sticker 01',
            last_seen: '2021-01-01',
            battery: 100,
            status: 'active',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
          {
            device_id: '2',
            device_name: 'RAK Sticker 02',
            last_seen: '2021-01-01',
            battery: 100,
            status: 'active',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
          {
            device_id: '3',
            device_name: 'RAK Sticker 03',
            last_seen: '2021-01-01',
            battery: 100,
            status: 'active',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
        ],
        columns: [
          {
            column_name: 'Device Name',
            column_type: 'string',
            field: 'device_name',
          },
          {
            column_name: 'Device ID',
            column_type: 'string',
            field: 'device_id',
          },
        ],
        conditions: [],
      },
      {
        id: '9',
        type: WidgetType.Gauge,
        widget_info: {
          name: 'Battery Level',
          appearance: {
            show_value: true,
          },
        },
        source: {
          type: GaugeType.Circular,
          device_id: '1',
          field: 'battery',
          min: 0,
          max: 100,
          decimal: 0,
          values: [
            {
              color: '99D689',
              value: 0,
            },
            {
              value: 84,
              color: 'cecece',
            },
          ],
          unit: '%',
        },
      },
      {
        id: '10',
        title: 'Camera DMZ 01-1511-M01',
        type: WidgetType.Camera,
      },
      {
        id: '11',
        title: 'Camera DMZ 01-1511-M02',
        type: WidgetType.Camera,
      },
      {
        id: '12',
        title: 'Distance Travelled Today',
        type: WidgetType.Progress,
        value: 50,
        unit: 'km',
        min: 0,
        color: '#8D9DF5',
        max: 100,
      },
      {
        id: '13',
        title: 'Son - Sticker',
        type: WidgetType.Sensor,
        color: '#95e1d9',
        value: 'On',
      },
      {
        id: '14',
        title: 'Theft Movement Alert',
        type: WidgetType.Switch,
        color: '#95e1d9',
      },
    ],
    layouts: {
      sm: SMART_FLEET_MONITOR_LAYOUT,
      md: SMART_FLEET_MONITOR_LAYOUT,
      lg: SMART_FLEET_MONITOR_LAYOUT,
      xl: SMART_FLEET_MONITOR_LAYOUT,
      xxl: SMART_FLEET_MONITOR_LAYOUT,
    },
  },
  {
    id: uuidv4(),
    dashboardId: 2,
    widgets: [
      {
        id: '1',
        type: WidgetType.Text,
        content: 'This dashboard is used to manage all the RAK Stickers',
      },
      {
        id: '2',
        type: WidgetType.Chart,
        title: 'Battery Usage Trend (RAK Sticker 01)',
        showXGrid: true,
        orientation: Orientation.Left,
        format: TimeFormat.TIME_24H,
        hideAxis: false,
        sources: [
          {
            legend: 'Battery Usage',
            field: 'battery',
            color: 'A0CFE1',
            show_legend: true,
            chart_type: ChartType.AreaChart,
            device_id: '1',
          },
        ],
      },
      {
        id: '3',
        type: WidgetType.Sensor,
        title: 'Distance Travelled Today',
        value: '50 km',
        color: '#8d9df5',
        sensor_type: 'distance',
      },
      {
        id: '4',
        type: WidgetType.Sensor,
        title: 'Current location',
        value: "107°17' - 108°20'",
        color: '#a0cfe1',
        sensor_type: 'location',
      },
      {
        id: '5',
        type: WidgetType.Gauge,
        widget_info: {
          name: 'Energy for DF ...',
          appearance: {
            show_value: true,
          },
        },
        source: {
          type: GaugeType.Circular,
          device_id: '1',
          field: 'battery',
          min: 100,
          max: 300,
          decimal: 0,
          values: [
            {
              color: '99D689',
              value: 0,
            },
            {
              value: 84,
              color: 'cecece',
            },
          ],
          unit: '%',
        },
      },
      {
        id: '6',
        title: 'New Slider Widget',
        type: WidgetType.Progress,
        value: 50,
        unit: 'ml',
        min: 0,
        color: '#F27877',
        max: 100,
      },
      {
        id: '7',
        type: WidgetType.Table,
        widget_info: {
          name: 'Geofencing Alerts',
          appearance: {
            show_value: true,
          },
        },
        source: [
          {
            device_id: '1',
            device_name: 'RAK Sticker 01',
            last_seen: '2021-01-01',
            battery: 60,
            status: 'active',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
          {
            device_id: '2',
            device_name: 'RAK Sticker 02',
            last_seen: '2021-01-01',
            battery: 70,
            status: 'active',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
          {
            device_id: '3',
            device_name: 'RAK Sticker 03',
            last_seen: '2021-01-01',
            battery: 100,
            status: 'active',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
          {
            device_id: '4',
            device_name: 'RAK Sticker 04',
            last_seen: '2021-01-01',
            battery: 10,
            status: 'inactive',
            coordinate: [16.061307485294005, 108.23972422618492],
          },
        ],
        columns: [
          {
            column_name: 'Device Name',
            column_type: 'string',
            field: 'device_name',
          },
          {
            column_name: 'Battery',
            column_type: 'number',
            field: 'battery',
          },
          {
            column_name: 'Status',
            column_type: 'string',
            field: 'status',
          },
        ],
        conditions: [
          {
            field: 'battery',
            operator: OPERATORS.GreaterThan,
            value: 80,
            bg_color: 'DBECC0',
          },
          {
            field: 'active',
            operator: OPERATORS.NotEquals,
            value: 'active',
            bg_color: 'FAAFC6',
          },
        ],
      },
      {
        id: '8',
        title: 'New Slider Widget',
        type: WidgetType.Progress,
        value: 50,
        unit: 'ml',
        min: 0,
        color: '#F27877',
        max: 100,
      },
      {
        id: '9',
        title: 'Camera DMZ 01-1511-M01',
        type: WidgetType.Camera,
      },
      {
        id: '10',
        title: 'Camera DMZ 01-1511-M02',
        type: WidgetType.Camera,
      },
      {
        id: '11',
        type: WidgetType.Map,
        title: 'Current Location',
        latitude: 16.05198423790203,
        longitude: 108.21679652348709,
        map_type: 'map',
      },
    ],
    layouts: {
      sm: CUSTOM_COLOR_LAYOUT,
      md: CUSTOM_COLOR_LAYOUT,
      lg: CUSTOM_COLOR_LAYOUT,
      xl: CUSTOM_COLOR_LAYOUT,
      xxl: CUSTOM_COLOR_LAYOUT,
    },
  },
  {
    id: uuidv4(),
    dashboardId: 3,
    widgets: [
      {
        id: '1',
        title: 'Camera DMZ 01-1511-M01',
        type: WidgetType.Camera,
      },
      {
        id: '2',
        title: 'Camera DMZ 01-1511-M02',
        type: WidgetType.Camera,
      },
      {
        id: '3',
        title: 'Camera DMZ 01-1511-M02',
        type: WidgetType.Camera,
      },
      {
        id: '4',
        type: WidgetType.Chart,
        title: 'Battery Usage Trend (RAK Sticker 01)',
        showXGrid: true,
        orientation: Orientation.Left,
        format: TimeFormat.TIME_24H,
        hideAxis: false,
        sources: [
          {
            legend: 'Battery Usage',
            field: 'battery',
            show_legend: true,
            chart_type: ChartType.AreaChart,
            device_id: '1',
            color: '171717',
          },
        ],
      },
      {
        id: '5',
        type: WidgetType.Sensor,
        title: 'Distance Travelled Today',
        value: '50 km',
        color: '#151718',
        sensor_type: 'distance',
      },
      {
        id: '6',
        type: WidgetType.Sensor,
        title: 'Current location',
        value: "107°17' - 108°20'",
        color: '#151718',
        sensor_type: 'location',
      },
      {
        id: '7',
        type: WidgetType.Gauge,
        widget_info: {
          name: 'Energy for DF ...',
          appearance: {
            show_value: true,
          },
        },
        source: {
          type: GaugeType.Circular,
          device_id: '1',
          field: 'battery',
          min: 0,
          max: 100,
          decimal: 0,
          values: [
            {
              color: '000',
              value: 0,
            },
            {
              value: 84,
              color: 'cecece',
            },
          ],
          unit: '%',
        },
      },
      {
        id: '8',
        type: WidgetType.Unit,
        title: 'Current Speed',
        value: 70,
        unit: 'km/h',
        status: 'On',
      },
      {
        id: '9',
        type: WidgetType.Unit,
        title: 'Total Trip',
        value: 12,
        unit: 'trips',
      },
      {
        id: '10',
        type: WidgetType.Unit,
        title: 'Min. Speed of today',
        value: 0,
        unit: 'km/h',
      },
      {
        id: '11',
        type: WidgetType.Unit,
        title: 'AVG. Speed of today',
        value: 84,
        unit: 'km/h',
      },
      {
        id: '12',
        type: WidgetType.Unit,
        title: 'Max. Speed of today',
        value: 125,
        unit: 'km/h',
      },
      {
        id: '13',
        type: WidgetType.Map,
        title: 'Current Location',
        latitude: 16.05198423790203,
        longitude: 108.21679652348709,
        map_type: 'map',
      },
    ],
    layouts: {
      sm: DEFAULT_MONITOR_LAYOUT,
      md: DEFAULT_MONITOR_LAYOUT,
      lg: DEFAULT_MONITOR_LAYOUT,
      xl: DEFAULT_MONITOR_LAYOUT,
      xxl: DEFAULT_MONITOR_LAYOUT,
    },
  },
]
