import AppProvider from '@/components/providers'
import { authOptions } from '@/lib/auth'
import '@/styles/globals.css'
import { Locale } from '@/types/global'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { routing } from '@/i18n/routing'

import { Plus_Jakarta_Sans } from 'next/font/google'
import { notFound } from 'next/navigation'

import 'mapbox-gl/dist/mapbox-gl.css'

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Space DF',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: Locale }
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound()
  }

  const messages = await getMessages()

  const session = await getServerSession(authOptions)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={plus_jakarta_sans.className}>
        <NextIntlClientProvider messages={messages}>
          <AppProvider session={session}>{children}</AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
